name: Build & Test .NET API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      SOLUTION_FILE: ToDoList.sln
      DOTNET_CLI_TELEMETRY_OPTOUT: "true"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Cache NuGet
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.fsproj', '**/*.vbproj', 'global.json', '**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore
      run: dotnet restore $SOLUTION_FILE

    - name: Build (Release)
      run: dotnet build $SOLUTION_FILE --configuration Release --no-restore

    - name: Test (entire solution)
      run: dotnet test $SOLUTION_FILE --configuration Release --no-build --collect "XPlat Code Coverage" --logger "trx;LogFileName=test_results.trx"

    - name: Upload test results (sempre)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/TestResults/*.trx
          **/TestResults/*/coverage.cobertura.xml
